### ISSUE TITLE
Create capture to unify makeshift actions

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-talon#10]
We have several actions that set selection and then run a VSCode command.  For example:

https://github.com/pokey/cursorless-talon/blob/4e1fc294dc278fe7e39860fd90aced559266db0d/src/cursorless.talon#L6-L21

We could unify these commands using a list like:

```py
ctx.lists["self.cursorless_makeshift_action"] = {
    "def show": "editor.action.revealDefinition",
    "ref show": "references-view.find",
}
```

And then we could replace most of the commands by:

```
<user.cursorless_makeshift_action> <user.cursorless_target>:
    user.cursorless_set_selection_then_run_command(cursorless_target, cursorless_makeshift_action)
```

Then implement `cursorless_set_selection_then_run_command` to set selection and run the command.  It could take an optional sleep length to let it also replace the quickfix command, that requires a sleep

Tbh we could even have a cursorless action that takes a command as an argument and do it extension-side.  But the point is once we have this capture set up we have more flexibility to tweak it

This change may improve DFA compilation time and will make it easier to include these commands in cheatsheet

_Originally posted by @pokey in https://github.com/pokey/cursorless-talon/pull/4#discussion_r661442716_

**Comment by AndreasArvidsson** [comment]
It would be nice to be able to do it extension side. Couldn't extract variable action be updated to take which kind of action as an additional parameter?
Then we could have quick fix, rename, everything in there

**Comment by pokey** [comment]
Yeah that can be a next step. We could also fairly easily make them appear like proper actions talon side and then just use a base class extension side

But getting them into a list is a good first step and has similar impact on DFA compilation
