### ISSUE TITLE
Not recognising colour/shape modifiers

### ISSUE THREAD

**Issue by elichad** [pokey/cursorless-talon#100]
If I say for example "copy blue drum," this is being processed as "copy drum," i.e. the colour modifier is lost. The same seems to happen for all colours and shapes. The individual colours/shapes were definitely enabled when I tested this (and the relevant markers were present on screen).

The colour and shape names are recognised just fine by Dragon in normal dictation so I don't think it's my pronunciation.

In addition (I'm not sure if this is related), the "take" command isn't being registered for me, even though Dragon definitely recognises it as the word "take" – instead of running the cursorless command "take blue urge" it just writes the words as dictation. I haven't tested other commands to "take" and "copy" so don't know if this is widespread.

**Comment by pokey** [comment]
This is probably related to cursorless not being able to find your settings.json.  I'll publish a fix for this. In the meantime, would be helpful to scan your log for output related to vscode / cursorless / settings.json and paste what you find here so we can come up with a workaround

Also, I'm surprised that you're able to use cursorless with dragon.  I had thought that the grammar was too big for dragon to handle

**Comment by elichad** [comment]
Talon is handling the cursorless commands but using Dragon for recognition. I've had no problems with the size of the grammar.

After restarting both VS Code and Talon, it's now working as expected. I guess this is because I updated cursorless today and something just needed to be picked up anew.

**Comment by pokey** [comment]
Ah ok cool glad to hear!  I'll close this one in favour of #91 then
