### ISSUE TITLE
Replace try/except with hasattr

### ISSUE THREAD

**Issue by AndreasArvidsson** [pokey/cursorless-talon#117]
Today we used the following pattern:
```
try:
    m.cursorless_modifier
except AttributeError:
    m.cursorless_another_modifier
```

We might want to change into:
```
if hasattr(m, "cursorless_modifier"):
    m.cursorless_modifier
else:
    m.cursorless_another_modifier
```

Am not convinced of which pattern is best at this time. I just wanted to raise the question.

**Comment by pokey** [comment]
I've been using the `try` / `except` style as [EAFP](https://docs.python.org/3/glossary.html) is generally more pythonic. But see [here](https://devblogs.microsoft.com/python/idiomatic-python-eafp-versus-lbyl/) for a more nuanced discussion. Could see a case made for either direction. Kinda depends what we're trying to convey with the control flow, eg what is "expected" vs "exceptional"

**Comment by AndreasArvidsson** [comment]
So basically the intent is that is it a normal use case or the exception that the key is missing. In many of our cases its a or statement between the two different keys where both can be as equally likely. I think that the try except pattern we have works fine.
