### ISSUE TITLE
"bring line X past line Y" copies the entire region between X and Y

### ISSUE THREAD

**Issue by seabadger** [pokey/cursorless-talon#147]
This is with v0.25.0 of the extension , and talon-side cursorless commit 5f295aaa4150309466186c6f41348043905d7bbe

**Comment by AndreasArvidsson** [comment]
That is by design. If you just want the two lines should say `bring line X and Y`

@pokey If you have migrated all the issues to the extension side you should probably disable them here

**Comment by pokey** [comment]
I believe "bring line X to Y" is what you're after here 😊

**Comment by AndreasArvidsson** [comment]
`bring line X to after Y`

Your very welcome :)

**Comment by seabadger** [comment]
Thanks, will try.
BTW, I believe "after" is missing from the docs, it occurs once in an
example, but is not actually explained like "pre", "past", etc. are.

**Comment by AndreasArvidsson** [comment]
If you look in the cheat sheet ie `cursorless help` you find it under positions.
