### ISSUE TITLE
Make cheat sheet sizing dynamic

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-talon#15]
Well no. It can absolutely be too wide for some screens. The only solution for that would be to adapt the font size depending on the user screen resolution

_Originally posted by @AndreasArvidsson in https://github.com/pokey/cursorless-talon/pull/1#discussion_r666427836_

**Comment by pokey** [comment]
I think the idea would be to render the cheatsheet with width 0 first in order to measure it, then render it with the proper width.  Right @AndreasArvidsson ?

**Comment by AndreasArvidsson** [comment]
That's one approach I'm going to try. Figuring out the correct font size based on the user screen resolution is more problematic.

**Comment by AndreasArvidsson** [comment]
@pokey It's tze döne!

**Comment by pokey** [comment]
weird it didn't auto-close.  Maybe you need to say "closes #15" instead of "issue #15"?  Idk
