### ISSUE TITLE
Add missing things to cheatsheet

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-talon#17]
- [x] the makeshift actions now have their own list but I didn’t add them to cheatsheet yet
- [x] and still missing the other actions from cursorless.talon
- [ ] and a list of wraps would be useful

**Comment by AndreasArvidsson** [comment]
There really isn't that much room for a list of wraps.

**Comment by pokey** [comment]
Last checkbox covered in #67 so let's close this one
