### ISSUE TITLE
Add action term override csv

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-talon#40]
we could have a file where you have your overrides in the form of `term,actionName`, and then if you have one for a given `actionName`, it will unlink the default one. This file could be stored outside the cursorless talon directory, and hopefully this would obviate the need for cursorless forks in most cases

**Comment by AndreasArvidsson** [comment]
1. Do we want to support renaming of other things than action names? Scope types comes to mind.
2. Do we want dynamic reloading when the csv file changes? Or is just startup okay?

**Comment by pokey** [comment]
> 1. Do we want to support renaming of other things than action names? Scope types comes to mind.

Yeah I'd say so.  Let's try to make it generic enough to support a few things.  At least action names and scope types.  I personally would be tempted to rename "inside" and "outside" in my repo as I don't love the two-syllable thing

> 2. Do we need dynamic reloading when the csv file changes? Or is just startup okay?

Dynamic reloading would def be preferred if it's not super difficult to impl

> 3. What should we do with actions that are not in the simple actions list? eg bring, swap?

Yeah it's a good question, because it kinda depends how we want the override to look.  Probably the most stable approach is to have entries where `actionName` corresponds to the extension-side name, but that does make it more difficult to handle non-simple actions.  What if we introduce a layer of indirection whereby every term in cursorless (at least the ones we want to remap) maps from term to internal name, so that then the user can map their own term to the given internal name

> 4. How are the users going to know the correct action name? In the cheat sheet we at least capitalize them and in some cases even rewrite them for clarity. Mapping new action named to old action name might be easier.

Yeah problem with mapping old action name is that we may want to change the defaults, tho that's def a backwards compatibility pain.  If we commit to not changing terms going forward I think we can get away with mapping at spoken form level, but not sure if we wanna make that commitment.  Hmm

**Comment by pokey** [comment]
Closed by #63
