### ISSUE TITLE
Get "change" / "replace" action working again

### ISSUE THREAD

**Issue by pokey** [pokey/cursorless-talon#58]
We disabled the "replace" command because we couldn't figure out a good way to make it work with DFA times. The "replace T with X" form of the command adds about 30-50ms. However, using the "change T word X" form causes DFA compilation times to increase by over 200ms. We will also probably want to add "insert" at the same time. 

We can then add "add" with same syntax "add T word X", but by default will modify T to have an "after". In the future, it will be its own action (see https://github.com/pokey/cursorless-vscode/issues/210)

**Comment by AndreasArvidsson** [comment]
@pokey Can we close this one?

**Comment by pokey** [comment]
Yes. As discussed, there are many ways one might insert text, and users will often have their own custom ways of doing so. Thus, we prefer to let users use "clear" (which we've now renamed by default to "change"), followed by their own text commands. In the future we'll add a robust "cursor back" command to make it easy to move somewhere, insert text, then return. So this issue's "change air word hello" will just become "change air word hello back", but in exchange for the extra syllable, the user will be able to replace "word hello" with any text editing commands that their user scripts support
