### ISSUE TITLE
The `clear` command clashes with Knausj commands

### ISSUE THREAD

**Issue by awulkan** [pokey/cursorless-talon#68]
Using the Knausj command `clear 1 until 9` results in this error.
![First error image](https://i.imgur.com/NtgYuyJ.png)

Saying `clear one` triggers the Knausj command and clears line 1 instead of the number highlighted by Cursorless.
![Second error image](https://i.imgur.com/U3cPSC4.png)

**Comment by pokey** [comment]
I think probably a good solution here is to change "clear" to "change" by default, as mentioned in #66
