### ISSUE TITLE
Shapes on first line can be cut off

### ISSUE THREAD

**Issue by SCdF** [pokey/cursorless-talon#93]
![image](https://user-images.githubusercontent.com/583851/137488041-c2e88780-72df-4d6e-938d-55ccaffff77a.png)

**Comment by AndreasArvidsson** [comment]
The solution was beyond simple. Just add this to your settings: `"editor.padding.top": 5`

**Comment by pokey** [comment]
Nice find. A few questions:

- Do we want to have cursorless set this by default? 
- Does this setting add extra unnecessary padding when you do have a code lens?
- Should we document this solution somewhere or just expect users to find this issue?

**Comment by AndreasArvidsson** [comment]
1.  Sounds good
2. No idea. i Dont have code lenses so cant tell
3. If not 1 then yes.

**Comment by pokey** [comment]
Closed by #390
